version: "3"
services:
    redis:
        image: redis:5.0
        container_name: redis
        networks:
            - meghasandesham-main
        volumes:
            - type: volume
              source: redisdata
              target: /var/lib/redis

    postgres:
        build:
            context: ../
            dockerfile: ./docker/postgres/Dockerfile
        container_name: postgres
        # environment:
        #     - POSTGRES_PASSWORD=password --optional if you are creating other databases (as a part of sql file that was copied inside initdb.d file)
        networks:
            - meghasandesham-main
        volumes:
            - type: volume
              source: postgresdata
              target: /var/lib/postgresql/data # by default postgres stored data in this file.. so we need to replace this path with our created volume.. so the data is stored in postgresql container as well as mirrored into volume
        # ports:
        #     - 5432:5432 #Before executing with this, ensure local postgres is stopped, so that host port 5432 is available
    app:
        container_name: meghasandesham
        build:
            context: ../
            #dockerfile: ./docker/app/Dockerfile
            dockerfile: ./docker/app/multistage/Dockerfile
            #dockerfile: ./docker/app/multistage/minimalistic-base/Dockerfile
            
            target: finalstage #this is not present in plain Dockerfile


        depends_on:
            - redis
            - postgres
            - authentication-service
        entrypoint: [] #["bash", "-c"]
        command: dockerize -wait tcp://redis:6379 -wait tcp://postgres:5432 -timeout 180s bash -c "echo please create an app start script && chmod +x run-app.sh && sh run-app.sh"
                #run a bash file which starts the app and the app's prerequisite command
        
        restart: on-failure
        networks:
            - meghasandesham-main
        ports:
            - 3100:3100
    
    authentication-service:
        image: ashishsv029/authentication-service:1.0.0
        container_name: authentication-service
        depends_on:
            - postgres
        command: dockerize -wait tcp://postgres:5432 -timeout 180s bash -c "echo able to connect to postgres"
        networks:
            - meghasandesham-main
        ports:
            - 3200:3200
        

networks:
    meghasandesham-main:
        driver: bridge

volumes:
    redisdata:
    postgresdata:

      

